### PR TITLE
Postgres User Defined Types support + some minor bug fixes

### PR DESCRIPTION
**Pull request by elemen3**
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'`

### CODE REVIEW

**Comment by elemen3** [comment]
Added support to generate dart type definitions from Postgres **User Defined Types** (Custom Data Types).

**Comment by elemen3** [comment]
There is a problem generating source files when the builder is dealing with array fields.  it puts `??` after the variable and causes formatting/parsing error.    please try it with **supabase** (`realtime` schema). you will face errors generating `Subscription` and `WalRls` tables.

Screen Shot 2022-02-06 at 1 14 49 PM

**Comment by osaxma** [comment]
> There is a problem generating source files when the builder is dealing with array fields (jsonb, ...) 

I just fixed that in #2 ..

---

This PR is trying to do two separate things -- can we focus on the original issue here and file a separate PR for updating the query? 

I need sometime to examine and review the query so having it in a separate PR will not delay fixing the original issue.


Also, I left a review comment for the original issue -- I'm not sure if you've missed it. 

---

Thanks for contributing and finding the bugs.

**Comment by osaxma** [comment]
Also, could you please create a branch other than `main` for the next PR. I'm unable to checkout into yours locally because it's conflicting with repo's `main`.

**Comment by elemen3** [comment]
I will close this request and will start with a new branch.

**Comment by elemen3** [comment]
Can't create a branch and create a PR based on my branch on your repo. Do you need to add me as a collaborator?

**Pull request closed without merging**
